#!/usr/bin/env bash
# --------------------------------------------------------------------------
# Lock the session.
# --------------------------------------------------------------------------

# Print the command's help text.
help() {
    cat <<EOF
Usage: mac lock

  Lock the session.

Flags:
  --help            Display this help text and exit.
EOF
}

# Parse the command's arguments.
case "$1" in
    --help)
        help
        exit 0
        ;;
    "")
        /System/Library/CoreServices/Menu\ Extras/User.menu/Contents/Resources/CGSession -suspend
        ;;
    *)
        echo "Error: unsupported command argument."
        exit 1
        ;;
esac
