#!/usr/bin/env bash
# --------------------------------------------------------------------------
# Put the computer to sleep.
# --------------------------------------------------------------------------

# Print the command's help text.
help() {
    cat <<EOF
Usage: mac sleep

  Put the computer to sleep.

Flags:
  --help            Display this help text and exit.
EOF
}

# Parse the command's arguments.
case "$1" in
    --help)
        help
        exit 0
        ;;
    "")
        pmset sleepnow
        ;;
    *)
        echo "Error: unsupported command argument."
        exit 1
        ;;
esac
