#!/usr/bin/env bash
# --------------------------------------------------------------------------
# Set the Xcode version to use on the command line.
# --------------------------------------------------------------------------

# Print the command's help text.
help() {
    cat <<EOF
Usage: mac xcode [ARGUMENTS]

  Select the Xcode version to use on the command line.

Arguments:
  <version>         One of 'release', 'beta'.

Flags:
  --help            Display this help text and exit.
EOF
}

# Parse the command's arguments.
case "$1" in
    ""|--help)
        help
        exit 0
        ;;
    release)
        sudo xcode-select -s /Applications/Xcode.app
        ;;
    beta)
        sudo xcode-select -s /Applications/Xcode-beta.app
        ;;
    *)
        echo "Error: unsupported argument."
        exit 1
        ;;
esac
