#!/usr/bin/env bash
set -euo pipefail

print_help() {
    cat <<EOF
Usage: dot backup <command>

  Run a backup script.

Flags:
  -h, --help            Print this help text and exit.

Backup \$HOME Commands:
  alpha                 Backup all files from HOME to Alpha (SSD).
  beta                  Backup all files from HOME to Beta (DHD).
  borg                  Backup important files from HOME to rsync.net.

Backup Disk Commands:
  a2b, alpha2beta       Backup content from Alpha (SSD) to Beta (DHD).
  b2g, beta2gamma       Backup content from Beta (DHD) to Gamma (PHD).
  b2d, beta2delta       Backup 'Backups' from Beta (DHD) to Delta (PHD).
EOF
}

if test "$#" = "0"; then
    print_help
    exit 0
fi

for arg in "$@"; do
    case "$arg" in
        alpha)
            ~/.dotfiles/scripts/backup-disk.sh Alpha
            ;;
        beta)
            ~/.dotfiles/scripts/backup-disk.sh Beta
            ;;
        borg)
            ~/.dotfiles/scripts/backup-borg.sh
            ;;
        b2g|beta2gamma)
            ~/.dotfiles/scripts/backup-beta2gamma.sh
            ;;
        b2d|beta2delta)
            ~/.dotfiles/scripts/backup-beta2delta.sh
            ;;
        a2b|alpha2beta)
            ~/.dotfiles/scripts/backup-alpha2beta.sh
            ;;
        ""|--help|-h)
            print_help
            exit 0
            ;;
        *)
            echo "Error: unsupported command."
            exit 1
            ;;
    esac
done
