#!/usr/bin/env bash
set -euo pipefail

print_help() {
    cat <<EOF
Usage: dot template <type> [directory]

  Initializes a new project directory from a template.

  If [directory] is specified, creates a new directory. Otherwise, initializes
  the current directory.

Templates:
  $(ls -m "$HOME/.dotfiles/templates")

Flags:
  -h, --help    Print this help text and exit.
EOF
}

if test "$#" = 0 || test "$1" = "--help" || test "$1" = "-h"; then
    print_help
    exit 0
fi

if test "$#" -gt 2; then
    print_help
    exit 1
fi

if test "$#" = 2; then
    mkdir -p "$2"
    cd "$2"
fi

if test -d "$HOME/.dotfiles/templates/$1"; then
    cp -R "$HOME/.dotfiles/templates/$1/" .
else
    echo "Error: no template for '$1'."
    exit 1
fi
