# ------------------------------------------------------------------------------
# Bootstrap file for the dotfiles installation.
#
# In theory, this file should be loaded by 'interactive login shells', e.g.
# when logging in remotely via ssh. OSX seems to treat new terminal windows
# as login shells.
# ------------------------------------------------------------------------------

source ~/.dotfiles/admin/boot.sh

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!
__conda_setup="$('/Users/dmulholl/dev/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "/Users/dmulholl/dev/miniconda3/etc/profile.d/conda.sh" ]; then
        . "/Users/dmulholl/dev/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="/Users/dmulholl/dev/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup
# <<< conda initialize <<<

