
# ----------------------------------------------------------------------------
# Bootstrap file for the dotfiles installation
# ----------------------------------------------------------------------------

# This file should be loaded by interactive login shells, e.g. when logging
# in remotely via ssh. OSX seems to treat new Terminal windows as login
# shells.

# Hand over control to the .bashrc file.
[[ -r ~/.bashrc ]] && source ~/.bashrc
