# ------------------------------------------------------------------------------
# Bootstrap file for the dotfiles installation.
#
# In theory, this file should be loaded by 'interactive non-login shells'.
# ------------------------------------------------------------------------------

source ~/.dotfiles/admin/boot.sh
