
" -------------------------------------------------------------------------
" Vim Settings
" -------------------------------------------------------------------------

" Allow backspace in insert mode.
set backspace=indent,eol,start

" Turn on syntax highlighting.
syntax enable

" Solarized Colorscheme.
" set background=dark
" let g:solarized_termcolors=256
" colorscheme solarized

" Show line numbers.
set number

" The default is 8.
set history=100

" Reload files changed outside Vim.
set autoread

" Always show the status line.
set laststatus=2

" Allow hidden buffers.
set hidden

" Indentation.
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set tabstop=4
set expandtab

" Don't wrap lines.
set nowrap

" Load language plugins and indent files.
filetype plugin indent on

" Scrolling.
set scrolloff=10
set sidescrolloff=15
set sidescroll=1

" Use case-sensitive search IFF the pattern contains uppercase letters.
set smartcase

" Alternative to using the escape key.
inoremap jj <ESC>
