" --------------------------------------------------------------------------
" Vim Settings
" --------------------------------------------------------------------------

" Allow backspace in insert mode.
set backspace=indent,eol,start

" Turn on syntax highlighting.
syntax enable

" Colorscheme.
colorscheme dusk

" The default is 8 commands.
set history=9999

" Reload files changed outside Vim.
set autoread

" Always show the status line.
set laststatus=2

" Allow hidden buffers.
set hidden

" Indentation.
set autoindent
set smartindent
set smarttab
set shiftwidth=4
set tabstop=4
set expandtab

" Don't wrap lines.
set nowrap

" Load language plugins and indent files.
filetype plugin indent on

" Vertical scrolling.
set scrolloff=5

" Use case-sensitive search IFF the pattern contains uppercase letters.
set ignorecase
set smartcase

" Find the next match as the search term is being typed.
set incsearch

" Highlight search matches.
set hlsearch

" Alternative to using the escape key.
inoremap jj <ESC>

" Remap the <leader> key for custom shortcuts.
let mapleader="\<Space>"

" Shortcut for re-sourcing the .vimrc file.
map <leader>rr :source ~/.vimrc<cr>

" Navigating splits.
" nnoremap <C-J> <C-W><C-J> " move down
" nnoremap <C-K> <C-W><C-K> " move up
" nnoremap <C-H> <C-W><C-H> " move left
" nnoremap <C-L> <C-W><C-L> " move right

" Customize the status line.
set statusline=
set statusline+=\ %n            " buffer number
set statusline+=\ %t            " tail of the filename
set statusline+=\ %m            " modified flag
set statusline+=%=              " left-right separator
set statusline+=\ %4l/%L        " current line / total lines
set statusline+=\ %3v           " column number
set statusline+=\ \ [%{&fo}]    " format options
set statusline+=\               " trailing space

" Treat files with a .stx extension as markdown.
autocmd BufNewFile,BufRead *.stx set filetype=markdown

" Turn on line numbers and relative line numbers.
set number
set relativenumber

" Show absolute line numbers when in insert mode.
autocmd InsertEnter * :set norelativenumber
autocmd InsertLeave * :set relativenumber

" Show absolute line numbers when we lose the focus. GUI only.
autocmd FocusLost * :set norelativenumber
autocmd FocusGained * :set relativenumber

" Toggle between relative and absolute line numbering.
nnoremap <silent><leader>n :set relativenumber!<cr>
