#!/usr/bin/env bash
set -euo pipefail

print_help() {
    cat <<EOF
Usage: dot clean <type>

  Deletes build artifacts from the current directory.

Flags:
  -h, --help    Print this help text and exit.

Types:
  latex
  python
EOF
}

if test "$#" = 0 || test "$1" = "--help" || test "$1" = "-h"; then
    print_help
    exit 0
fi

if test "$#" -gt 1; then
    print_help
    exit 1
fi

find . -name ".DS_Store" -delete
find . -name "._.DS_Store" -delete
find . -name "._*" -delete
find . -name ".*.swp" -delete

if test "$1" == "python" || test "$1" == "py"; then
    find . -name "*.egg-info" -exec rm -r "{}" +
    find . -name "__pycache__" -exec rm -r "{}" +
    find . -name ".pytest_cache" -exec rm -r "{}" +
    find . -name "*.pyc" -delete
    find . -name "dist" -exec rm -r "{}" +
    find . -name "build" -exec rm -r "{}" +
fi

if test "$1" == "latex"; then
    find . -name "*.aux" -delete
    find . -name "*.toc" -delete
    find . -name "*.out" -delete
    find . -name "*.lof" -delete
    find . -name "*.log" -delete
    find . -name "*.lot" -delete
    find . -name "*.dvi" -delete
    find . -name "*.fls" -delete
    find . -name "*.xdv" -delete
    find . -name "*.fdb_latexmk" -delete
    find . -name "*.bbl" -delete
    find . -name "*.blg" -delete
fi
