#!/usr/bin/env bash
set -euo pipefail

print_help() {
    cat <<EOF
Usage: dot init <type>

  Initializes the current directory from a project template.

Templates:
  $(ls -m "$HOME/.dotfiles/templates")

Flags:
  -h, --help    Print this help text and exit.
EOF
}

if test "$#" = 0 || test "$1" = "--help" || test "$1" = "-h"; then
    print_help
    exit 0
fi

if test "$#" -gt 1; then
    print_help
    exit 1
fi

if test -d "$HOME/.dotfiles/templates/$1"; then
    cp -R "$HOME/.dotfiles/templates/$1/" .
else
    echo "Error: no template for '$1'."
    exit 1
fi
